/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppQuestsRouteImport } from './routes/_app/quests'
import { Route as AppGuildsIndexRouteImport } from './routes/_app/guilds/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppGuildsSlugRouteImport } from './routes/_app/guilds/$slug'
import { Route as AppGuildsSlugIndexRouteImport } from './routes/_app/guilds/$slug/index'
import { Route as AppGuildsSlugSettingsRouteImport } from './routes/_app/guilds/$slug/settings'
import { Route as AppGuildsSlugQuestsRouteImport } from './routes/_app/guilds/$slug/quests'
import { Route as AppGuildsSlugMembersRouteImport } from './routes/_app/guilds/$slug/members'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsIndexRoute = AppGuildsIndexRouteImport.update({
  id: '/guilds/',
  path: '/guilds/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuildsSlugRoute = AppGuildsSlugRouteImport.update({
  id: '/guilds/$slug',
  path: '/guilds/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppGuildsSlugIndexRoute = AppGuildsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGuildsSlugRoute,
} as any)
const AppGuildsSlugSettingsRoute = AppGuildsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppGuildsSlugRoute,
} as any)
const AppGuildsSlugQuestsRoute = AppGuildsSlugQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppGuildsSlugRoute,
} as any)
const AppGuildsSlugMembersRoute = AppGuildsSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppGuildsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quests': typeof AppQuestsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invite/$code': typeof InviteCodeRoute
  '/guilds/$slug': typeof AppGuildsSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds/': typeof AppGuildsIndexRoute
  '/guilds/$slug/members': typeof AppGuildsSlugMembersRoute
  '/guilds/$slug/quests': typeof AppGuildsSlugQuestsRoute
  '/guilds/$slug/settings': typeof AppGuildsSlugSettingsRoute
  '/guilds/$slug/': typeof AppGuildsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quests': typeof AppQuestsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/invite/$code': typeof InviteCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/guilds': typeof AppGuildsIndexRoute
  '/guilds/$slug/members': typeof AppGuildsSlugMembersRoute
  '/guilds/$slug/quests': typeof AppGuildsSlugQuestsRoute
  '/guilds/$slug/settings': typeof AppGuildsSlugSettingsRoute
  '/guilds/$slug': typeof AppGuildsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/quests': typeof AppQuestsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_app/guilds/$slug': typeof AppGuildsSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/guilds/': typeof AppGuildsIndexRoute
  '/_app/guilds/$slug/members': typeof AppGuildsSlugMembersRoute
  '/_app/guilds/$slug/quests': typeof AppGuildsSlugQuestsRoute
  '/_app/guilds/$slug/settings': typeof AppGuildsSlugSettingsRoute
  '/_app/guilds/$slug/': typeof AppGuildsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quests'
    | '/login'
    | '/register'
    | '/invite/$code'
    | '/guilds/$slug'
    | '/api/auth/$'
    | '/guilds/'
    | '/guilds/$slug/members'
    | '/guilds/$slug/quests'
    | '/guilds/$slug/settings'
    | '/guilds/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quests'
    | '/login'
    | '/register'
    | '/invite/$code'
    | '/api/auth/$'
    | '/guilds'
    | '/guilds/$slug/members'
    | '/guilds/$slug/quests'
    | '/guilds/$slug/settings'
    | '/guilds/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/quests'
    | '/_auth/login'
    | '/_auth/register'
    | '/invite/$code'
    | '/_app/guilds/$slug'
    | '/api/auth/$'
    | '/_app/guilds/'
    | '/_app/guilds/$slug/members'
    | '/_app/guilds/$slug/quests'
    | '/_app/guilds/$slug/settings'
    | '/_app/guilds/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteCodeRoute: typeof InviteCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/': {
      id: '/_app/guilds/'
      path: '/guilds'
      fullPath: '/guilds/'
      preLoaderRoute: typeof AppGuildsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/guilds/$slug': {
      id: '/_app/guilds/$slug'
      path: '/guilds/$slug'
      fullPath: '/guilds/$slug'
      preLoaderRoute: typeof AppGuildsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guilds/$slug/': {
      id: '/_app/guilds/$slug/'
      path: '/'
      fullPath: '/guilds/$slug/'
      preLoaderRoute: typeof AppGuildsSlugIndexRouteImport
      parentRoute: typeof AppGuildsSlugRoute
    }
    '/_app/guilds/$slug/settings': {
      id: '/_app/guilds/$slug/settings'
      path: '/settings'
      fullPath: '/guilds/$slug/settings'
      preLoaderRoute: typeof AppGuildsSlugSettingsRouteImport
      parentRoute: typeof AppGuildsSlugRoute
    }
    '/_app/guilds/$slug/quests': {
      id: '/_app/guilds/$slug/quests'
      path: '/quests'
      fullPath: '/guilds/$slug/quests'
      preLoaderRoute: typeof AppGuildsSlugQuestsRouteImport
      parentRoute: typeof AppGuildsSlugRoute
    }
    '/_app/guilds/$slug/members': {
      id: '/_app/guilds/$slug/members'
      path: '/members'
      fullPath: '/guilds/$slug/members'
      preLoaderRoute: typeof AppGuildsSlugMembersRouteImport
      parentRoute: typeof AppGuildsSlugRoute
    }
  }
}

interface AppGuildsSlugRouteChildren {
  AppGuildsSlugMembersRoute: typeof AppGuildsSlugMembersRoute
  AppGuildsSlugQuestsRoute: typeof AppGuildsSlugQuestsRoute
  AppGuildsSlugSettingsRoute: typeof AppGuildsSlugSettingsRoute
  AppGuildsSlugIndexRoute: typeof AppGuildsSlugIndexRoute
}

const AppGuildsSlugRouteChildren: AppGuildsSlugRouteChildren = {
  AppGuildsSlugMembersRoute: AppGuildsSlugMembersRoute,
  AppGuildsSlugQuestsRoute: AppGuildsSlugQuestsRoute,
  AppGuildsSlugSettingsRoute: AppGuildsSlugSettingsRoute,
  AppGuildsSlugIndexRoute: AppGuildsSlugIndexRoute,
}

const AppGuildsSlugRouteWithChildren = AppGuildsSlugRoute._addFileChildren(
  AppGuildsSlugRouteChildren,
)

interface AppRouteChildren {
  AppQuestsRoute: typeof AppQuestsRoute
  AppGuildsSlugRoute: typeof AppGuildsSlugRouteWithChildren
  AppGuildsIndexRoute: typeof AppGuildsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppQuestsRoute: AppQuestsRoute,
  AppGuildsSlugRoute: AppGuildsSlugRouteWithChildren,
  AppGuildsIndexRoute: AppGuildsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteCodeRoute: InviteCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
